version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_local
    restart: always
    environment:
      POSTGRES_USER: rrosero
      POSTGRES_PASSWORD: rrosero
      POSTGRES_DB: data_migration_gl
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: